### ISSUE TITLE
[Feature Request] Threshold events

### ISSUE THREAD

**Issue by jschloer** [wix/react-native-interactable#24]
I have a similar use case to #18 where I want to use interactable for a drawer, but in our case, the drawer pops in when you select a pin on a map, but goes completely off screen when you close it. The problem I'm running into is there is a couple second delay while the animation settles, before onSnap is received. I'm essentially destroying the interactable view after receiving the onSnap event, but if the user clicks another pin before the animation finishes, the component isn't actually destroyed and puts us in a weird state where the interactable is off screen, but our app thinks it's visible. 
I was wondering if you would consider a pull request to add vertical/horizontal thresholds. Basically whenever the center point crosses the threshold(like near the bottom of the screen), fire a thresholdCrossed event, with a threshold id, similar to onSnap. I believe this would need to go in both the IntereactableView and the PhysicsAnimator. Does this sound right? Is there a simpler solution I'm missing? Thanks for the great library!

**Comment by talkol** [comment]
this is an important feature, I wanted to add it for a while. It has a lot of power because you could also change all the physics rules when a threshold is crossed (consider springs disappearing and appearing in other places when you move around, just by using setState).

what would the API look like?

I thought about using a declaration similar to `frictionAreas`, but it will be called something like `alertAreas`, and whenever the center enters an area, you will be notified with something like an `onAlertArea` event. The nice thing about areas is that they're very flexible. They can be a small square somewhere or half the screen (just giving `left` for example)

**Comment by jschloer** [comment]
I see you self assigned this, but let me know if there's anything I can do to help. I definitely think alertAreas are more powerful than the thresholds I was suggesting.

**Comment by talkol** [comment]
@jschloer I implemented the `alertAreas` for iOS in this commit https://github.com/wix/react-native-interactable/commit/3660d635f52a5b59301ff2347990b9fab821e4f8

Take a look, there's an example too that prints these events to console

If you want to help, you can maybe port this to Android? please do your best to keep a direct port as possible with identical function names so maintainability is easier

**Comment by jschloer** [comment]
Submitted as #33.

**Comment by talkol** [comment]
Merged by @rotemmiz so I'm closing, please reopen if I missed something
